version: '3'
services:
  mongodb:
    container_name: starwars-mongodb
    image: mongo:4.2
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - production-network

  appserver:
    container_name: starwars-api
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - production-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: starwars
    depends_on:
      - mongodb

networks:
  production-network:
    driver: bridge
