spring.application.name=Star Wars API
spring.mongodb.uri=mongodb://localhost:27017/starwars_db
# RestClient
restclient.pool.connection-request-timeout=1000
restclient.pool.connect-timeout=5000
restclient.pool.socket-timeout=300
restclient.pool.max-connections=20
restclient.pool.max-per-route=6
restclient.pool.validate-after-inactivity=30
restclient.pool.retry-count=1
restclient.pool.retry-sleep-time-MS=20

# StarWars API
starwars.api.url=https://swapi.dev/api/planets?search=

# Circuit Breaker
swapi.circuit-breaker.failure-rate-threshold=30
swapi.circuit-breaker.slow-call-duration-threshold-ms=800
swapi.circuit-breaker.slow-call-rate-threshold=50
swapi.circuit-breaker.wait-duration-in-open-state-seconds=60
swapi.circuit-breaker.sliding-window-size=10
swapi.circuit-breaker.minimum-number-of-calls=3
swapi.circuit-breaker.permitted-number-of-calls-in-half-open-state=3

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=1h

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
