name: Star Wars Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21 from Amazon Corretto
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --fail-at-end --file pom.xml
    - name: Publish test report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        fail_on_failure: true
